model:
  src_vocab: 128
  trg_vocab: 128
  d_model: 128
  N: 8
  heads: 1
  dropout: 0.2
  dis: 0.5
  map_com_itels: 1
train:
  label_pth: /home/hust/yly/Dataset/all.json
  feat_extract_model_path: /home/hust/yly/Model/mix_mot17_half_dla34.pth
  down_rate: 4
  max_len: 30
  device: cuda
  base_lr: 0.001
  start_epoch: 1
  batch_size: 192
  num_workers: 1
  load_model: ''
  num_epochs: 100
  save_all: False
  lr_step:
    - 25
    - 50
    - 75
  save_dir: /home/hust/yly/Model
  num_iters: -1
  logdir: /home/hust/yly/log
  mode: record
  file: /home/hust/yly/featmap.json
  min_frames: 30
  max_frames: 30
val:
  val_intervals: 25
  device: cuda
  feat_extract_model_path: /home/hust/yly/Model/mix_mot17_half_dla34.pth
  down_rate: 4
  max_len: 30
  label_pth: /home/hust/yly/Dataset/mot15.json
  batch_size: 16
  file: /home/hust/yly/featmapmot15.json
  min_frames: 30
  max_frames: 30 

